package com.simbirsoft.sailclient.util;

public enum UserPreferenceKey {
    LAYOUT_X, LAYOUT_Y, PREF_WIDTH, PREF_HEIGHT,
    ADDRESS_LAYOUT_X, ADDRESS_LAYOUT_Y, ADDRESS_PREF_WIDTH, ADDRESS_PREF_HEIGHT,
    CATEGORY_LAYOUT_X, CATEGORY_LAYOUT_Y, CATEGORY_PREF_WIDTH, CATEGORY_PREF_HEIGHT,
    TOTAL_LAYOUT_X, TOTAL_LAYOUT_Y, TOTAL_PREF_WIDTH, TOTAL_PREF_HEIGHT
}
